version: "3"

services:
  users: 
    build: ./user-service

  clients: 
    build: ./client-service


  nginx:
    image: nginx:latest
    ports:
      - "9090:9090"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - users
      - clients